export interface SeatInstanceLayout {
  x: number;
  y: number;
  size: number;
  rotation: number;
  colorIndex: number;
  stateFlags: number;
}

export const SEAT_INSTANCE_STRIDE_BYTES = 24;
export const SEAT_INSTANCE_WORDS = 6;

export const SEAT_INSTANCE_X_OFFSET_BYTES = 0;
export const SEAT_INSTANCE_Y_OFFSET_BYTES = 4;
export const SEAT_INSTANCE_SIZE_OFFSET_BYTES = 8;
export const SEAT_INSTANCE_ROTATION_OFFSET_BYTES = 12;
export const SEAT_INSTANCE_COLOR_INDEX_OFFSET_BYTES = 16;
export const SEAT_INSTANCE_STATE_FLAGS_OFFSET_BYTES = 20;

export const SEAT_INSTANCE_FIELD_OFFSETS_BYTES = {
  x: SEAT_INSTANCE_X_OFFSET_BYTES,
  y: SEAT_INSTANCE_Y_OFFSET_BYTES,
  size: SEAT_INSTANCE_SIZE_OFFSET_BYTES,
  rotation: SEAT_INSTANCE_ROTATION_OFFSET_BYTES,
  colorIndex: SEAT_INSTANCE_COLOR_INDEX_OFFSET_BYTES,
  stateFlags: SEAT_INSTANCE_STATE_FLAGS_OFFSET_BYTES,
} as const;

export const SEAT_STATE_FLAG_SELECTED = 1 << 0;
export const SEAT_STATE_FLAG_HOVERED = 1 << 1;
export const SEAT_STATE_FLAG_UNAVAILABLE = 1 << 2;
export const SEAT_STATE_FLAG_DISABLED = 1 << 3;
export const SEAT_STATE_FLAG_HIGHLIGHTED = 1 << 4;
export const SEAT_STATE_FLAG_FOCUSED = 1 << 5;

export const SEAT_STATE_STATUS_CODE_SHIFT = 8;
export const SEAT_STATE_STATUS_CODE_MASK = 0xff << SEAT_STATE_STATUS_CODE_SHIFT;
export const SEAT_STATE_RESERVED_MASK = (0xffff0000 | (0x3 << 6)) >>> 0;

export const SEAT_STATE_FLAGS = {
  SELECTED: SEAT_STATE_FLAG_SELECTED,
  HOVERED: SEAT_STATE_FLAG_HOVERED,
  UNAVAILABLE: SEAT_STATE_FLAG_UNAVAILABLE,
  DISABLED: SEAT_STATE_FLAG_DISABLED,
  HIGHLIGHTED: SEAT_STATE_FLAG_HIGHLIGHTED,
  FOCUSED: SEAT_STATE_FLAG_FOCUSED,
} as const;
